name: KE-${project.name}
version: ${project.version}
author: Ninjoh

depend: [KE-ModItem,KE-ModCore,KE-ModPlayerClass,NinCore]
main: tk.martijn_heil.kingdomessentials.command.KingdomEssCommand

commands:
   kingdomessentials:
      aliases: [kingdomkits,kk,ke]
      description: The main command for this plugin.
      usage: /<command>