name: KE-${project.name}
version: ${project.version}
author: Ninjoh

depend: [NinCore]
main: tk.martijn_heil.kingdomessentials.command.ModCommand
commands:
   kingdomessentials:
      aliases: [kingdomkits,kk,ke]
      description: The main command for this plugin.
      usage: /<command>