name: ${project.parent.name}${project.name}
version: ${project.version}
author: Ninjoh

depend: [KingdomEssItem,KingdomEssCore]
main: tk.martijn_heil.KindgomEssentials.command.KingdomEssCommand

commands:
   kingdomess:
      aliases: [kingdomkits,kk,ke,]
      description: The main command for this plugin.
      usage: /<command>