# Classes section
classes:

  # Enable classes?
  enabled: true

  # Should the player's class kit be given upon respawn?
  # This also gives a freshly joined player his kit.
  giveKitOnRespawn: true

  # Default class for players
  defaultClass: 'footsoldier'

  # Cool down between class switches in minutes
  # Default value(1440) is 1 day exact.
  coolDownInMinutes: 1440

  # If a player changes faction; should his
  # player class be reset to the default player class?
  # Note: Only works if factions integration is enabled.
  setPlayerClassToDefaultOnFactionChange: true


  # Classes are defined below
  # Essentials kits are used for the kits.
  # WARNING: Do not name a class "default"
  #
  # You should not include a leading slash in any commands executed on respawn.
  # You may use variables in commandsExeCutedOnPlayerRespawn. You may use the following variables;
  #
  # {player_name}         | The player's Minecraft username.
  # {player_uuid}         | The player's uuid.
  # {player_displayname}  | The player's displayname.
  classes:
    footsoldier:
      kitName: 'footsoldier'
      useMaxPercentagePerFaction: true
      maxPercentagePerFaction: 100
      commandsExecutedOnPlayerRespawn: []
    archer:
      kitName: 'archer'
      useMaxPercentagePerFaction: true
      maxPercentagePerFaction: 50
      commandsExecutedOnPlayerRespawn: []
    knight:
      kitName: 'knight'
      useMaxPercentagePerFaction: false
      maxPercentagePerFaction: 100
      commandsExecutedOnPlayerRespawn: []
    lord:
      kitName: 'lord'
      useMaxPercentagePerFaction: false
      maxPercentagePerFaction: 100
      commandsExecutedOnPlayerRespawn: []
