name: KE-ModIllegalActions
version: @version@
author: Ninjoh

main: tk.martijn_heil.kingdomessentials.illegalactions.ModIllegalActions
depend: [KE-ModItem,NinCore]

permissions:
  kingdomess.illegalactions.bypass.potion.disable:
    default: false