name: ${project.parent.name}${project.name}${project.name}
version: ${project.version}
author: Ninjoh

main: tk.martijn_heil.kingdomessentials.illegalactions.KingdomEssIllegalActions
depend: [KingdomEssItem]